version: '3.8'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    container_name: postgres_cont
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres-data: