name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
#        env:
#          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#        run: |
#          docker buildx build \
#           --no-cache \
#           --platform linux/amd64,linux/arm64 \
#           -t sdec2000/website-image:latest \
#           -t sdec2000/website-image:$GITHUB_SHA \
#           --push \
#            .
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: sdec2000/website
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

